import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Server Actions MongoDB",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-200">
        <main className="bg-white max-w-3xl p-5 min-h-[100dvh] mx-auto py-10 flex flex-col ">
          <ul className="w-full bg-slate-900 text-white uppercase p-5 mb-6 flex flex-row gap-5">
            <li>
              <Link href={"/"} className="flex hover:text-slate-300">
                Home
              </Link>
            </li>
            <li>
              <Link href={"/user"} className="flex hover:text-slate-300">
                User
              </Link>
            </li>
          </ul>

          {children}
        </main>
        <Toaster
          position="bottom-right"
          toastOptions={{
            duration: 3000,
            style: {
              background: "#363636",
              color: "#fff",
            },
          }}
        />
      </body>
    </html>
  );
}
